Migrate master to MN4
micronaut-projects/micronaut-pulsar pull request #297
Opened 2023-02-01 16:33 UTC by wetted

closes #282

2023-02-01 22:39 UTC, wetted commented
@harissecic Can you tell why these tests are failing now? I am on a M1 mac so – unfortunately – I cannot run the tests: they try to bind to a protected directory on my mac, even if I run them using testcontainers.cloud. As a result the testcontainer fails to startup.

I have pretty everything migrated to enable this as a module for Micronaut 4, including all the renovate dependendency updates, and fixes for depreacations introduced by Micronaut 4 core.

2023-02-02 06:22 UTC, sdelamo requested changes

2023-02-02 06:22 UTC, sdelamo commented on build.gradle
> +//plugins {
if it is not necessary remove commented out code.

2023-02-02 06:22 UTC, sdelamo commented on buildSrc/src/main/groovy/io.micronaut.build.internal.pulsar-base.gradle
> +//configurations.all {
if it is not necessary remove commented out code.

2023-02-02 06:22 UTC, sdelamo commented on gradle/libs.versions.toml
> +groovy = "4.0.7"
```suggestion
groovy = "4.0.8"
```

2023-02-02 06:22 UTC, sdelamo commented on gradle/libs.versions.toml
> +#kotlin-jvm = { id = 'org.jetbrains.kotlin.jvm', version.ref = 'kotlin' }
if not necessary remove commented out code

2023-02-02 06:22 UTC, sdelamo commented
@wetted it fails in CI

2023-02-02 08:02 UTC, harissecic commented
> @harissecic Can you tell why these tests are failing now? I am on a M1 mac so – unfortunately – I cannot run the tests: they try to bind to a protected directory on my mac, even if I run them using testcontainers.cloud. As a result the testcontainer fails to startup.
> 
> I have pretty everything migrated to enable this as a module for Micronaut 4, including all the renovate dependendency updates, and fixes for depreacations introduced by Micronaut 4 core.

For some reason beans are not initialized for tests. In the same class that's failing, for example:
```
PulsarConsumerSpec > test consumer read default topic and array FAILED |  
  | io.micronaut.context.exceptions.NoSuchBeanException at PulsarConsumerSpec.groovy:48
```
there's a bean at the bottom. Not sure if upgrades made my code not see test defined inner classes in groovy or is it because of Java modules, or maybe `spec.name` should be changed. I need to investigate.

For  your case it might be that I need to change tests (not sure how) to somehow generate file in the test container for Pulsar which should have replaced some values for configuring broker and client (StandaloneConf for pulsar with all-in-one container and ClientConf for brokers communicating with each other in test-share-module). My problem is that I had issues with files in the JAR and moving those to containers so I let Java tests create temp files and copy them to Pulsar container. If you have a better way of doing this let me know. Maybe I don't need to change these values and I can somehow have hardcoded files but I still need a way to copy them to container without issues on Linux based and Windows OS. Windows is probably least important since most devs use Mac or Linux (or WSL on Windows if not directly Linux) but I don't have a Mac to test different setups for file copy.

Anyway I will investigate but I would require some help on how to copy file from build folder to container under TestContainers so that it works on all platforms.

2023-02-02 16:48 UTC, harissecic commented
@wetted I've managed to fix Micronaut not finding beans in test which was due to removal of some dependencies. Now their back (annotation processing). I've also changed how files work so maybe you'll be able to use it on your Mac now. One thing I still need to fix but not sure how is missing `JsonMapper` from Micronaut. Bean is not available and I don't know which dependency should be added to configure it. Easiest solution would be to instantiate it locally and add to application context in tests but I don't want to do that if there's a dependency that does this from micronaut-serde or such

2023-02-02 17:51 UTC, wetted commented
@harissecic The reason I cannot run the tests try to bind to my mac at `/var/folders/7w/q4klm5d94hxcb_5dtxqmq84w0000gp/T/5393098636774802321.tmp\` but that's a protected directory, so the container fails to start.

```
java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName(Class.java:467)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at io.micronaut.pulsar.PulsarAwareTest.setupSpec(PulsarAwareTest.groovy:32)
Caused by: java.lang.Exception: 
	at io.micronaut.pulsar.shared.PulsarTls.<clinit>(PulsarTls.groovy:60)
	... 3 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at app//org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at app//io.micronaut.pulsar.shared.PulsarTls.<clinit>(PulsarTls.groovy:58)
	... 3 more
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at app//org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	... 5 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at app//org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
	at app//org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at app//org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 6 more
Caused by: com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/var/folders/7w/q4klm5d94hxcb_5dtxqmq84w0000gp/T/5393098636774802321.tmp\" to rootfs at \"/pulsar/conf/client.conf\": mount /var/folders/7w/q4klm5d94hxcb_5dtxqmq84w0000gp/T/5393098636774802321.tmp:/pulsar/conf/client.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"}
```

2023-02-02 17:54 UTC, harissecic commented
> @harissecic The reason I cannot run the tests try to bind to my mac at `/var/folders/7w/q4klm5d94hxcb_5dtxqmq84w0000gp/T/5393098636774802321.tmp\` but that's a protected directory, so the container fails to start. See the last line of the following stack trace.
> 
> ```
> java.lang.ExceptionInInitializerError
> 	at java.base/java.lang.Class.forName(Class.java:467)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
> 	at io.micronaut.pulsar.PulsarAwareTest.setupSpec(PulsarAwareTest.groovy:32)
> Caused by: java.lang.Exception: 
> 	at io.micronaut.pulsar.shared.PulsarTls.<clinit>(PulsarTls.groovy:60)
> 	... 3 more
> Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
> 	at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
> 	at app//org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
> 	at app//io.micronaut.pulsar.shared.PulsarTls.<clinit>(PulsarTls.groovy:58)
> 	... 3 more
> Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
> 	at app//org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
> 	at app//org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
> 	... 5 more
> Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
> 	at app//org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
> 	at app//org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
> 	at app//org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
> 	... 6 more
> Caused by: com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/var/folders/7w/q4klm5d94hxcb_5dtxqmq84w0000gp/T/5393098636774802321.tmp\" to rootfs at \"/pulsar/conf/client.conf\": mount /var/folders/7w/q4klm5d94hxcb_5dtxqmq84w0000gp/T/5393098636774802321.tmp:/pulsar/conf/client.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"}
> ```

Latest push from me to this branch should avoid temp files and allow file from gradle resource build dir to just change permission to rwx for all. Not sure will it fix this but it should be a different path at least

2023-02-02 18:02 UTC, wetted commented
> Latest push from me to this branch should avoid temp files and allow file from gradle resource build dir to just change permission to rwx for all. Not sure will it fix this but it should be a different path at least

I will check. I also think I know what's causing some test failures (I missed something in the migration). I will grab your changes and see if I can fix it.

2023-02-02 18:23 UTC, wetted commented
@harissecic your changes don't seem to help, although the stacktrace shows the changed directories.

```
Caused by: com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/Users/wetted/Development/projects/micronaut/micronaut-pulsar/test-suite/test-pulsar-module/build/resources/test/standalone.conf\" to rootfs at \"/pulsar/conf/standalone.conf\": mount /Users/wetted/Development/projects/micronaut/micronaut-pulsar/test-suite/test-pulsar-module/build/resources/test/standalone.conf:/pulsar/conf/standalone.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"}

```

2023-02-02 18:33 UTC, wetted commented
I still can't run tests locally, but I fixed them for CI and they all now pass. This is ready for review and merge, but running on M1 Mac with Ventura 13.2 still doesn't work for me.

2023-02-02 19:28 UTC, harissecic approved these changes
This is fine for now I think. It's only tests for local dev on Mac or tightened security systems that are going to fail. I've added file permission change into the test for standalone.conf and client.conf from resource build directory. On Mac I guess you have to explicitly add those files to shared part in Docker - or use Linux VM.

2023-02-02 20:40 UTC, wetted commented
> This is fine for now I think. It's only tests for local dev on Mac or tightened security systems that are going to fail. I've added file permission change into the test for standalone.conf and client.conf from resource build directory. On Mac I guess you have to explicitly add those files to shared part in Docker - or use Linux VM.

Thank you for your contribution and feedback.

2023-02-15 08:42 UTC, merged